server:
  port: 8085

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost-8091:8091/eureka/,http://localhost-8092:8092/eureka/,http://localhost-8093:8093/eureka/

spring:
  application:
    name: config-service
  cloud:
    loadbalancer:
      retry:
        enabled: false
  profiles:
    active: native
