server:
  port: 8083

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:8080/eureka
    registerWithEureka: true
    fetchRegistry: false

spring:
  application:
    name: server-service
  cloud:
    loadbalancer:
      retry:
        enabled: false
    inetutils:
      timeout-seconds: 10