server:
  port: 8092

eureka:
  instance:
    hostname: localhost-8092
  client:
    #     声明是否将自己的信息注册到 Eureka 服务器上
    registerWithEureka: true
    #     是否到 Eureka 服务器中抓取注册信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost-8091:8091/eureka/,http://localhost-8092:8092/eureka/,http://localhost-8093:8093/eureka/


spring:
  application:
    name: eurka-service
  security:
    user:
      name: @eureka.user.name@
      password: @eureka.user.password@
      roles: SUPERUSER