server:
  port: 8093

eureka:
  instance:
    hostname: localhost-8093
  client:
    #     声明是否将自己的信息注册到 Eureka 服务器上
    registerWithEureka: true
    #     是否到 Eureka 服务器中抓取注册信息
    fetchRegistry: true
    serviceUrl:
      defaultZone:  http://@eureka.user.name@:@eureka.user.password@@localhost:8091/eureka/,http://@eureka.user.name@:@eureka.user.password@@localhost:8092/eureka/,http://@eureka.user.name@:@eureka.user.password@@localhost:8093/eureka/


spring:
  application:
    name: eurka-service
  security:
    user:
      name: @eureka.user.name@
      password: @eureka.user.password@
      roles: SUPERUSER