server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    #     声明是否将自己的信息注册到 Eureka 服务器上
    registerWithEureka: true
    #     是否到 Eureka 服务器中抓取注册信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:8080/eureka/


spring:
  application:
    name: service-consumer
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2

#服务名
server-provider:
  ribbon:
    ConnectTimeout: 250 #单位ms,请求连接超时时间
    ReadTimeout: 1000 #单位ms,请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数

