server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    #     声明是否将自己的信息注册到 Eureka 服务器上
    registerWithEureka: true
    #     是否到 Eureka 服务器中抓取注册信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:8080/eureka/


spring:
  application:
    name: service-consumer
